# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['title'], 'verbose_name': 'Разделы', 'verbose_name_plural': 'Разделы'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['num', 'title'], 'verbose_name': 'Объекты', 'verbose_name_plural': 'Объекты'},
        ),
    ]
