# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 08:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20170407_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', sorl.thumbnail.fields.ImageField(blank=True, upload_to='gallery', verbose_name='Изображение')),
                ('youtube_url', embed_video.fields.EmbedVideoField(blank=True, verbose_name='Youtube адрес видео')),
                ('num', models.IntegerField(blank=True, db_index=True, default=0, verbose_name='Порядковый номер')),
                ('item', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='base.Item')),
            ],
            options={
                'verbose_name_plural': 'Изображения',
                'verbose_name': 'Изображение',
                'ordering': ['num'],
            },
        ),
    ]
