# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_itemphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.CharField(default='', max_length=12, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='item',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Товарный остаток'),
        ),
        migrations.AddField(
            model_name='item',
            name='borrowed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Заемные средства'),
        ),
        migrations.AddField(
            model_name='item',
            name='costs',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Расходы'),
        ),
        migrations.AddField(
            model_name='item',
            name='email',
            field=models.EmailField(default='', max_length=12, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='item',
            name='fio',
            field=models.CharField(default='', max_length=1000, verbose_name='Контактное лицо'),
        ),
        migrations.AddField(
            model_name='item',
            name='licenses',
            field=models.CharField(default='', max_length=1000, verbose_name='Лицензии и сертификаты'),
        ),
        migrations.AddField(
            model_name='item',
            name='means',
            field=models.CharField(default='', max_length=12, verbose_name='Средства производства'),
        ),
        migrations.AddField(
            model_name='item',
            name='part',
            field=models.CharField(default='', max_length=12, verbose_name='Доля'),
        ),
        migrations.AddField(
            model_name='item',
            name='phone',
            field=models.CharField(default='', max_length=12, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='item',
            name='profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Прибыль'),
        ),
        migrations.AddField(
            model_name='item',
            name='purchase',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость'),
        ),
        migrations.AddField(
            model_name='item',
            name='realty',
            field=models.IntegerField(choices=[(0, 'Нет'), (1, 'В аренде'), (2, 'В собственности')], default=0, verbose_name='Недвижимость'),
        ),
        migrations.AddField(
            model_name='item',
            name='receipts',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Выручка'),
        ),
        migrations.AddField(
            model_name='item',
            name='staff',
            field=models.CharField(default='', max_length=12, verbose_name='Персонал'),
        ),
    ]
