# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20170411_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='email',
            field=models.EmailField(default='', max_length=30, verbose_name='E-mail'),
        ),
    ]
